### ISSUE TITLE
Invalid type names?

### ISSUE THREAD

**Issue by Richard87** [rtk-incubator/rtk-query-codegen#15]
Hi!

I am running a API-Platform project, that uses a bunch of -,: in the type names, which makes typescript complain *alot* :) 

Stuff like this, any tips on how I can fix it?
![image](https://user-images.githubusercontent.com/5749715/104177937-e0546c00-5409-11eb-95c1-8976b1ce2135.png)

TSC Complains about the dash, and ] sign, but I have no idea what is needed to fix :/

**Comment by phryneas** [comment]
Can you provide us an api schema that reproduces this? Without it, this will be very difficult to find.

**Comment by Richard87** [comment]
Ofcourse, check out https://gist.github.com/Richard87/6ae23d5548894447fae6a9d54928b717 :)

**Comment by phryneas** [comment]
Thanks! I'll try to check it out this evening or tomorrow, currently at work.

**Comment by Richard87** [comment]
Thanks! Also, I love this work, super excited about it :D

**Comment by msutkowski** [comment]
@phryneas I wonder what a good way to handle this would be? We could consider introducing a config file that allows for multiple transformers? This is going to be different for everyone, and I don't really see a reliable way to do this internally, but essentially, a user would need to be able to provide a function that transformed weird names like this:

`ConsultationParticipant-Consultation:view`. This seems to be standard convention in this schema, so I'd want to be able to do something like:

```js transformers.js
module.exports = {
transformers: {
      queryArgType: (generatedName) => {
            // do further process of the generated internal type names here. in the case of this example, i'd want to do something like:
            return generatedOperationName.split(/[-:]+/).map(word => capitalize(word)).join(''); // output: ConsultationParticipantConsultationView 
      },
      responseType: () => {}
```

Relevant code:

```ts
const ResponseTypeName = factory.createTypeReferenceNode(
    registerInterface(
      factory.createTypeAliasDeclaration(
        undefined,
        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        capitalize(getOperationName(verb, path, operation.operationId) + responseSuffix),
        undefined,
        ResponseType
      )
    ).name
  );

  const QueryArg = factory.createTypeReferenceNode(
    registerInterface(
      factory.createTypeAliasDeclaration(
        undefined,
        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        capitalize(getOperationName(verb, path, operation.operationId) + argSuffix),
        undefined,
        factory.createTypeLiteralNode(
          Object.entries(queryArg).map(([name, def]) => {
            const comment = def.origin === 'param' ? def.param.description : def.body.description;
            const node = factory.createPropertySignature(
              undefined,
              name,
              createQuestionToken(!def.required),
              def.type
            );

            if (comment) {
              return ts.addSyntheticLeadingComment(node, ts.SyntaxKind.MultiLineCommentTrivia, `* ${comment} `, true);
            }
            return node;
          })
        )
      )
    ).name
  );
```

**Comment by phryneas** [comment]
I think as a quick win, it would probably be enough to replace all invalid characters by `_` or something like that. I'm not sure: do we need an upstream PR against ozapftis for that or will this be 100% doable on our side?

**Comment by msutkowski** [comment]
If we go with what I was mentioning, we control the output name, so we could just swap out:

`capitalize(getOperationName(verb, path, operation.operationId) + argSuffix)` -> `replaceCharsAndCapitalizeTokens(getOperationName(verb, path, operation.operationId) + argSuffix)` (or just loading that fn from a config file as mentioned)...

I don't think this would fall under ozapfts at all. I do think that everyone is going to have potentially weird outputs, so it makes sense to just offer a function for it, but I also think you're right about probably just stripping non-letter chars.

I guess there is always the increased possibility for collisions when doing a transformation this way, so it should probably be configurable? I'll think some more about it... anyone else have some ideas? :D

**Comment by Richard87** [comment]
Thanks for all the attention :) 

I like replacing special characters with _, but I'm not sure about this case:
```
export type COLLECTION_RESPONSE = /** status 200 AnswerSet collection response */ AnswerSet-AnswerSet:view[];
export typeITEM_RESPONSE = /** status 200 AnswerSet resource updated */ AnswerSet-AnswerSet:view;
```
Does [] have special meaning? If not, maybe we could rename [] to List, and replace other special characters to _

This would work nicely *for me*, but no idea what other side effects that would have :/

**Comment by kahirokunn** [comment]
Actually, I had the same problem before and have already sent a pull request to oazapfts for a fix, but no response.
https://github.com/cellular/oazapfts/pull/42

**Comment by kahirokunn** [comment]
@phryneas https://github.com/phryneas/oazapfts/pull/1
In fact, I've sent a similar pull request to you as well, since you've created a great fork.

**Comment by tevariou** [comment]
> @phryneas [phryneas/oazapfts#1](https://github.com/phryneas/oazapfts/pull/1)
> In fact, I've sent a similar pull request to you as well, since you've created a great fork.

I'm suggesting a new fix since it didn't solve the issue for me https://github.com/phryneas/oazapfts/pull/2
