### ISSUE TITLE
improve import path

### ISSUE THREAD

**Issue by kahirokunn** [rtk-incubator/rtk-query-codegen#27]
## Relative path to --file

When I tried the following command, it resulted in an invalid import because the path relative to A was not calculated.

```
npx @rtk-incubator/rtk-query-codegen-openapi --baseQuery @/libs/authQuery.ts:authQuery --file ./src/gen/rtk.ts -- ./path/to/swagger.yaml
```

## support path alias

So I tried path alias, but the path alias was trapped by fs.existsSync validation.

```
--baseQuery @/libs/authQuery.ts:authQuery
```

## Plan

step 1. set the file option to required and remove the std.out feature
step 2. if baseQuery is entered and not path alias, calculate the relative path to the path of file option and use it as import path
step 3. if baseQuery is entered and path alias is used, use it as import path without any validation

**Comment by kahirokunn** [comment]
@phryneas  @msutkowski what do you think?

**Comment by phryneas** [comment]
Hmm. I don't think we need to go that far. I would just make sure that *if* `--file` is specified and `baseQuery` is a relative path, it gets resolved correctly.

**Comment by kahirokunn** [comment]
@phryneas @msutkowski 
The current import path produced wrong results in my environment.
So I can't use the latest version. 😢 
I've made some improvements in this area, so please check it out!

https://github.com/rtk-incubator/rtk-query-codegen/pull/29
