### ISSUE TITLE
Add filter option to the CLI for operations

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query-codegen#3]
It would be great if we could specify what operations to include when generating a schema

**Comment by kahirokunn** [comment]
Is it a sufficient requirement to support regular expressions and exclude APIs with corresponding paths?

**Comment by phryneas** [comment]
The codegen is now published as `@rtk-query/codegen-openapi` and the code has moved over to [the Redux Toolkit monorepo](https://github.com/reduxjs/redux-toolkit/tree/master/packages/rtk-query-codegen-openapi).

As usage has changed as well, please [read the new documentation](https://redux-toolkit.js.org/rtk-query/usage/code-generation).


This issue should be solved there.
