### ISSUE TITLE
Docs issue: update baseQuery snippet in API docs

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query-codegen#34]
https://rtk-query-docs.netlify.app/api/createapi/#basequery Snippet needs to be updated per #33 

Ex:      `dispatch(setToken(refreshResult.data));` should be `api.dispatch(setToken(refreshResult.data));`

**Comment by tevariou** [comment]
Also I think baseQueryWithReauth should be async and the baseQuery call awaited in this example

**Comment by msutkowski** [comment]
@tevariou Mind opening a PR? If not, I'll get to it later :)
