### ISSUE TITLE
invalidate via OpenAPI

### ISSUE THREAD

**Issue by faragos** [rtk-incubator/rtk-query-codegen#36]
When you generate the API the invalidation is annoying to do because everytime you regenerate the Files the "invalidates" are missing. How about it generates the invalidates based on the 'tags'? I mean normally all "GET" provides and all others invalidate mostly. I'm not sure if this makes sense but it would be helpful for me at the moment at least 👍 

Love the codegen so far ❤️

**Comment by phryneas** [comment]
The idea is that you use a second file with `enhanceEndpoints` to add `provides`/`invalidates` on top of the generated file. So you should never need to touch the generated file.
See the example [in the docs](https://rtk-query-docs.netlify.app/concepts/code-generation)

As for automatically generating those, I don't think the OpenAPI standard does give any guidance on something like that, so before this comes out wrong in many cases I'd rather not do it at all.

**Comment by faragos** [comment]
Oh man was too hyped about the generation, that I didn't finish reading it there and searched for it in the [code-splitting](https://rtk-query-docs.netlify.app/concepts/code-splitting) 🤦 
Thank you for the fast response 👍
