### ISSUE TITLE
Option to generate hooks, but not export them

### ISSUE THREAD

**Issue by StefanBRas** [rtk-incubator/rtk-query-codegen#51]
Hi,

Short version: It would be nice if there was a way to generate the api using `createApi` from `@rtk-incubator/rtk-query/react` but without exporting all the hooks.

Longer version:
I have a project where we have use an api with a large amount of end points. As there are a lot of endpoints, I'll start by gradually migrating them, by using `enhanceEndpoints` on the generated api and then only exposing some of the hooks.
However if i use the `--hooks` option, it will by default export all of the hooks - if I don't use `--hooks` it will not use the  `createApi` from `@rtk-incubator/rtk-query/react` but the one from `@rtk-incubator/rtk-query` and thus i can't use hooks. 

We're talking maybe 100-ish endpoints, so it messes with autocompletion having all the hooks exported and it's then not clear which ones are properly migrated and which ones are not.

Kind regards,
Stefan

**Comment by phryneas** [comment]
We should probably just make the import path adjustable, as by now there is also an angular package for this.
