### ISSUE TITLE
Generate empty type for endpoints that don't require params

### ISSUE THREAD

**Issue by asherccohen** [rtk-incubator/rtk-query-codegen#53]
Context:
GET requests that don't need parameters are executed with a call to the query hook with empty brackets

`const {data} = useGetItemsQuery()`

or with undefined if options need to be passed:

`const {data} = useGetItemsQuery(undefined, {skip: true})`

Issue:
Types for these endpoints are generated like so:
`type GetItemsApiArg = {}`

Expected result:
Arg Types should be empty or unknown to allow for no required parameters.

PS. To a stretch, {} is always wrong in TS, either use `unknown ` or `Record<string, unknown>`

**Comment by tevariou** [comment]
`void` would be more appropriate i guess

**Comment by jordancarney1** [comment]
@ phryneas I took the liberty of taking a shot at a fix for this in #72

**Comment by JosNun** [comment]
Correct me if I'm wrong, but I don't think it's possible to pass in a second argument when the first argument is typed as void, is it? I had to cast something as `void` if I wanted to supply options to the hook.

```ts
const { data } = useGetSomething(
        undefined as void,
        {
            pollingInterval: 5 * 1_000,
        }
    );
```

**Comment by phryneas** [comment]
@JosNun `undefined` should be enough, no casting needed.

**Comment by JosNun** [comment]
Thanks! I officially feel dumb, now 😆 

That said, since #72 has been merged, this can probably be closed now, correct?

**Comment by phryneas** [comment]
Good point.
