### ISSUE TITLE
Allow config to specify an entry point

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query-codegen#66]
Might be partially [addressed here](https://github.com/rtk-incubator/rtk-query-codegen/issues/63) in the 'configuration file' concept, but as of now, the only way to use the react entry point is to specify hooks, which is clunky. IMO, these should both be configurable. For example, I should be able to specify:
- React, with hooks
- React, without hooks
- SomeFutureEntryPoint, with hooks (that solidjs demo I made had 'hooks' :sweat_smile: )
- SomeFutureEntryPoint, whatever.

If we're switching over to a config file in the next version, I imagine we'd want to establish a contract for entry points and hooks. Solid/svelte/vue/etc should all be able to support a version

**Comment by phryneas** [comment]
Nope nope nope :)
Let's throw *all* that away. 

We import a ready-configured `api` object from another file. The user can do what they want there, including importing stuff from `@someRandomPlanet/query` or using a different fetchBaseQuery. Whatever. Let this plugin just generate `injectApi` statements, types and exports.

**Comment by msutkowski** [comment]
Got it, sounds even more ideal :)
