### ISSUE TITLE
How to inject a custom base URL on runtime

### ISSUE THREAD

**Issue by sn3ek** [rtk-incubator/rtk-query-codegen#70]
Our web app connects to local networks which will be setup on runtime. Thus it is necessary to inject a base URL on runtime. 

What is the most elegant way to inject a base URL on runtime into the generated rtk-query stubs?

Thank you

**Comment by msutkowski** [comment]
You'd want to do this in a custom baseQuery. There is an example that gets you most of the way here: https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#constructing-a-dynamic-base-url-using-redux-state. In your case, you'd want to set `fetchBaseQuery({baseUrl: ''})`, then build the base url on each request.


Something close to what you need:
```ts

const rawBaseQuery = fetchBaseQuery({
  baseUrl: '',
});

const dynamicBaseQuery: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError
> = async (arg, api, extraOptions) => {
  let { config } = api.getState() as RootState;

  // Do something here to load your config if you're not keeping it in state, and loading it there.

  const originalUrl = typeof arg === 'string' ? arg : arg.url;

  const originalWithBaseUrl = `${config.API_URL}${originalUrl}`;

  const adjustedArgs =
    typeof arg === 'string'
      ? originalWithBaseUrl
      : { ...arg, url: originalWithBaseUrl };

  return rawBaseQuery(adjustedArgs, api, extraOptions);
};

export default dynamicBaseQuery;

**Comment by sn3ek** [comment]
Thank you!
