### ISSUE TITLE
option to configure codegen to override query/mutation builder type

### ISSUE THREAD

**Issue by mwarger** [rtk-incubator/rtk-query-codegen#73]
Related to this: https://github.com/reduxjs/redux-toolkit/issues/1532

I don't have a proposed solution to this, yet, just wanted to track it here for the future.

**Comment by phryneas** [comment]
I just implemented this over in the rehaul in #81 - could you please give that new version a try and report back?

**Comment by phryneas** [comment]
The codegen is now published as `@rtk-query/codegen-openapi` and the code has moved over to [the Redux Toolkit monorepo](https://github.com/reduxjs/redux-toolkit/tree/master/packages/rtk-query-codegen-openapi).

As usage has changed as well, please [read the new documentation](https://redux-toolkit.js.org/rtk-query/usage/code-generation).


As this repository is getting archived, I am going to close this issue - it should be resolved by the new codegen.
