### ISSUE TITLE
Properties are always set as nullable

### ISSUE THREAD

**Issue by JohnnyDP** [rtk-incubator/rtk-query-codegen#74]
When I run the generator all of the Typescript interfaces have all of their properties set as nullable (? notation).

The expectation was that all properties were not nullable unless they have the nullable property set to true.

https://swagger.io/specification/#schema-nullable

**Comment by phryneas** [comment]
That does not seem to be the case in this example: https://github.com/rtk-incubator/rtk-query-codegen/blob/main/test/fixtures/generated.ts

Could you provide a schema that acts as a reproduction for this?

**Comment by JohnnyDP** [comment]
Of course. 
The spec is generated using Swashbuckle

Im using this command for generation:
npx @rtk-incubator/rtk-query-codegen-openapi --hooks src/api/swagger.json > src/api/generated-rtkquery/rtkquery-api.ts

The spec.. (Generated TS below):

`{
  "openapi": "3.0.1",
  "info": {
    "title": "SePU.WebApplication",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    }
  ],
  "paths": {
    "/api/authenticate": {
      "post": {
        "tags": [
          "Authenticate"
        ],
        "operationId": "Authenticate",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthenticateRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudies": {
      "post": {
        "tags": [
          "CreateAnalysisStudy"
        ],
        "operationId": "CreateAnalysisStudy",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAnalysisStudyRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateAnalysisStudyResponse"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "GetAnalysisStudies"
        ],
        "operationId": "GetAnalysisStudies",
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/AnalysisStudyItem"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v0/GetAnalysis": {
      "get": {
        "tags": [
          "GetAnalysis"
        ],
        "operationId": "CreateSustainingFactor",
        "parameters": [
          {
            "name": "analysisId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateSustainingFactorRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "201": {
            "description": "Success"
          }
        }
      }
    },
    "/api/user-account": {
      "post": {
        "tags": [
          "CreateUserAccount"
        ],
        "operationId": "CreateUserAccount",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserAccountRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{analysisId}/SustainingFactorsPhase/SustainingFactor/{sustainingFactorId}": {
      "delete": {
        "tags": [
          "DeleteSustainingFactor"
        ],
        "operationId": "DeleteSustainingFactor",
        "parameters": [
          {
            "name": "analysisId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sustainingFactorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "204": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudies/{id}": {
      "get": {
        "tags": [
          "GetAnalysisStudy"
        ],
        "operationId": "GetAnalysisStudy",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AnalysisStudy"
                }
              }
            }
          }
        }
      }
    },
    "/api/refresh-token": {
      "post": {
        "tags": [
          "RefreshToken"
        ],
        "operationId": "RefreshToken",
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/revoke-token": {
      "post": {
        "tags": [
          "RevokeToken"
        ],
        "operationId": "RevokeToken",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RevokenTokenRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{id}/problemDescriptionPhase/empiricalFoundation": {
      "put": {
        "tags": [
          "UpdateEmpiricalFoundation"
        ],
        "operationId": "UpdateEmpiricalFoundation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateEmpiricalFoundationRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{id}/problemDescriptionPhase/goal": {
      "put": {
        "tags": [
          "UpdateGoal"
        ],
        "operationId": "UpdateGoal",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateGoalRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{id}/problemDescriptionPhase/objective": {
      "put": {
        "tags": [
          "UpdateObjective"
        ],
        "operationId": "UpdateObjective",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateObjectiveRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{id}/problemDescriptionPhase/problemDefinition": {
      "put": {
        "tags": [
          "UpdateProblemDefinition"
        ],
        "operationId": "UpdateProblemDefinition",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateProblemDefinitionRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{analysisId}/SustainingFactorsPhase/SustainingFactor/{sustainingFactorId}/description": {
      "put": {
        "tags": [
          "UpdateSustainingFactorDescription"
        ],
        "operationId": "UpdateSustainingFactorDescription",
        "parameters": [
          {
            "name": "analysisId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sustainingFactorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateDescriptionRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{analysisId}/SustainingFactorsPhase/SustainingFactor/{sustainingFactorId}/perceptiveType": {
      "put": {
        "tags": [
          "UpdateSustainingFactorPerceptiveType"
        ],
        "operationId": "UpdateSustainingFactorPerceptiveType",
        "parameters": [
          {
            "name": "analysisId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sustainingFactorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateSustainingFactorProducesRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/analysisStudy/{analysisId}/SustainingFactorsPhase/SustainingFactor/{sustainingFactorId}/selectedForAction": {
      "put": {
        "tags": [
          "UpdateSustainingFactorSelectedForAction"
        ],
        "operationId": "UpdateSustainingFactorSelectedForAction",
        "parameters": [
          {
            "name": "analysisId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sustainingFactorId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateSustainingFactorSelectedForActionRequest"
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValidationError"
                }
              }
            }
          },
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AnalysisStudy": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "title": {
            "type": "string"
          },
          "problemDescription": {
            "$ref": "#/components/schemas/ProblemDescription"
          }
        },
        "additionalProperties": false
      },
      "AnalysisStudyItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "title": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "AuthenticateRequest": {
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "Email for the useraccount"
          },
          "password": {
            "type": "string",
            "description": "Password for the useraccount"
          }
        },
        "additionalProperties": false,
        "description": "Model used to authenticate a useraccount"
      },
      "CreateAnalysisStudyRequest": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "CreateAnalysisStudyResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          }
        },
        "additionalProperties": false
      },
      "CreateSustainingFactorRequest": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "perceptiveType": {
            "$ref": "#/components/schemas/PerceptiveType"
          },
          "selectedForAction": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
      "CreateUserAccountRequest": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "Error": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "detail": {
            "type": "string"
          },
          "instance": {
            "type": "string"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          },
          "traceId": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "ErrorDetail": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "field": {
            "type": "string"
          },
          "attemptedValue": { },
          "message": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "PerceptiveType": {
        "enum": [
          "PerceptiveNotSelected",
          "Individual",
          "Context",
          "Participant"
        ],
        "type": "string"
      },
      "ProblemDescription": {
        "type": "object",
        "properties": {
          "goal": {
            "type": "string"
          },
          "problemDefinition": {
            "type": "string"
          },
          "empiricalFoundation": {
            "type": "string"
          },
          "objective": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "RevokenTokenRequest": {
        "type": "object",
        "properties": {
          "refreshToken": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "UpdateDescriptionRequest": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "UpdateEmpiricalFoundationRequest": {
        "type": "object",
        "properties": {
          "empiricalFoundation": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "UpdateGoalRequest": {
        "type": "object",
        "properties": {
          "goal": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "UpdateObjectiveRequest": {
        "type": "object",
        "properties": {
          "objective": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "UpdateProblemDefinitionRequest": {
        "type": "object",
        "properties": {
          "problemDefinition": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "UpdateSustainingFactorProducesRequest": {
        "type": "object",
        "properties": {
          "perceptiveType": {
            "$ref": "#/components/schemas/PerceptiveType"
          }
        },
        "additionalProperties": false
      },
      "UpdateSustainingFactorSelectedForActionRequest": {
        "type": "object",
        "properties": {
          "selectedForAction": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
      "ValidationError": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "detail": {
            "type": "string"
          },
          "instance": {
            "type": "string"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          },
          "traceId": {
            "type": "string"
          },
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ErrorDetail"
            }
          }
        },
        "additionalProperties": false
      }
    }
  }
}`

Generated TS:

`import { createApi } from "@reduxjs/toolkit/query/react";
import { fetchBaseQuery } from "@reduxjs/toolkit/query";
export const api = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:5000" }),
  tagTypes: [],
  endpoints: (build) => ({
    authenticate: build.mutation<AuthenticateApiResponse, AuthenticateApiArg>({
      query: (queryArg) => ({
        url: `/api/authenticate`,
        method: "POST",
        body: queryArg.authenticateRequest,
      }),
    }),
    createAnalysisStudy: build.mutation<
      CreateAnalysisStudyApiResponse,
      CreateAnalysisStudyApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudies`,
        method: "POST",
        body: queryArg.createAnalysisStudyRequest,
      }),
    }),
    getAnalysisStudies: build.query<
      GetAnalysisStudiesApiResponse,
      GetAnalysisStudiesApiArg
    >({
      query: () => ({ url: `/api/analysisStudies` }),
    }),
    createSustainingFactor: build.query<
      CreateSustainingFactorApiResponse,
      CreateSustainingFactorApiArg
    >({
      query: (queryArg) => ({
        url: `/api/v0/GetAnalysis`,
        body: queryArg.createSustainingFactorRequest,
      }),
    }),
    createUserAccount: build.mutation<
      CreateUserAccountApiResponse,
      CreateUserAccountApiArg
    >({
      query: (queryArg) => ({
        url: `/api/user-account`,
        method: "POST",
        body: queryArg.createUserAccountRequest,
      }),
    }),
    deleteSustainingFactor: build.mutation<
      DeleteSustainingFactorApiResponse,
      DeleteSustainingFactorApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.analysisId}/SustainingFactorsPhase/SustainingFactor/${queryArg.sustainingFactorId}`,
        method: "DELETE",
      }),
    }),
    getAnalysisStudy: build.query<
      GetAnalysisStudyApiResponse,
      GetAnalysisStudyApiArg
    >({
      query: (queryArg) => ({ url: `/api/analysisStudies/${queryArg.id}` }),
    }),
    refreshToken: build.mutation<RefreshTokenApiResponse, RefreshTokenApiArg>({
      query: () => ({ url: `/api/refresh-token`, method: "POST" }),
    }),
    revokeToken: build.mutation<RevokeTokenApiResponse, RevokeTokenApiArg>({
      query: (queryArg) => ({
        url: `/api/revoke-token`,
        method: "POST",
        body: queryArg.revokenTokenRequest,
      }),
    }),
    updateEmpiricalFoundation: build.mutation<
      UpdateEmpiricalFoundationApiResponse,
      UpdateEmpiricalFoundationApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.id}/problemDescriptionPhase/empiricalFoundation`,
        method: "PUT",
        body: queryArg.updateEmpiricalFoundationRequest,
      }),
    }),
    updateGoal: build.mutation<UpdateGoalApiResponse, UpdateGoalApiArg>({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.id}/problemDescriptionPhase/goal`,
        method: "PUT",
        body: queryArg.updateGoalRequest,
      }),
    }),
    updateObjective: build.mutation<
      UpdateObjectiveApiResponse,
      UpdateObjectiveApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.id}/problemDescriptionPhase/objective`,
        method: "PUT",
        body: queryArg.updateObjectiveRequest,
      }),
    }),
    updateProblemDefinition: build.mutation<
      UpdateProblemDefinitionApiResponse,
      UpdateProblemDefinitionApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.id}/problemDescriptionPhase/problemDefinition`,
        method: "PUT",
        body: queryArg.updateProblemDefinitionRequest,
      }),
    }),
    updateSustainingFactorDescription: build.mutation<
      UpdateSustainingFactorDescriptionApiResponse,
      UpdateSustainingFactorDescriptionApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.analysisId}/SustainingFactorsPhase/SustainingFactor/${queryArg.sustainingFactorId}/description`,
        method: "PUT",
        body: queryArg.updateDescriptionRequest,
      }),
    }),
    updateSustainingFactorPerceptiveType: build.mutation<
      UpdateSustainingFactorPerceptiveTypeApiResponse,
      UpdateSustainingFactorPerceptiveTypeApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.analysisId}/SustainingFactorsPhase/SustainingFactor/${queryArg.sustainingFactorId}/perceptiveType`,
        method: "PUT",
        body: queryArg.updateSustainingFactorProducesRequest,
      }),
    }),
    updateSustainingFactorSelectedForAction: build.mutation<
      UpdateSustainingFactorSelectedForActionApiResponse,
      UpdateSustainingFactorSelectedForActionApiArg
    >({
      query: (queryArg) => ({
        url: `/api/analysisStudy/${queryArg.analysisId}/SustainingFactorsPhase/SustainingFactor/${queryArg.sustainingFactorId}/selectedForAction`,
        method: "PUT",
        body: queryArg.updateSustainingFactorSelectedForActionRequest,
      }),
    }),
  }),
});
export type AuthenticateApiResponse = /** status 200 Success */ undefined;
export type AuthenticateApiArg = {
  authenticateRequest: AuthenticateRequest;
};
export type CreateAnalysisStudyApiResponse =
  /** status 201 Success */ CreateAnalysisStudyResponse;
export type CreateAnalysisStudyApiArg = {
  createAnalysisStudyRequest: CreateAnalysisStudyRequest;
};
export type GetAnalysisStudiesApiResponse =
  /** status 200 Success */ AnalysisStudyItem[];
export type GetAnalysisStudiesApiArg = void;
export type CreateSustainingFactorApiResponse =
  /** status 201 Success */ undefined;
export type CreateSustainingFactorApiArg = {
  analysisId: string;
  createSustainingFactorRequest: CreateSustainingFactorRequest;
};
export type CreateUserAccountApiResponse = /** status 200 Success */ undefined;
export type CreateUserAccountApiArg = {
  createUserAccountRequest: CreateUserAccountRequest;
};
export type DeleteSustainingFactorApiResponse =
  /** status 204 Success */ undefined;
export type DeleteSustainingFactorApiArg = {
  analysisId: string;
  sustainingFactorId: string;
};
export type GetAnalysisStudyApiResponse =
  /** status 200 Success */ AnalysisStudy;
export type GetAnalysisStudyApiArg = {
  id: string;
};
export type RefreshTokenApiResponse = /** status 200 Success */ undefined;
export type RefreshTokenApiArg = void;
export type RevokeTokenApiResponse = /** status 200 Success */ undefined;
export type RevokeTokenApiArg = {
  revokenTokenRequest: RevokenTokenRequest;
};
export type UpdateEmpiricalFoundationApiResponse =
  /** status 200 Success */ undefined;
export type UpdateEmpiricalFoundationApiArg = {
  id: string;
  updateEmpiricalFoundationRequest: UpdateEmpiricalFoundationRequest;
};
export type UpdateGoalApiResponse = /** status 200 Success */ undefined;
export type UpdateGoalApiArg = {
  id: string;
  updateGoalRequest: UpdateGoalRequest;
};
export type UpdateObjectiveApiResponse = /** status 200 Success */ undefined;
export type UpdateObjectiveApiArg = {
  id: string;
  updateObjectiveRequest: UpdateObjectiveRequest;
};
export type UpdateProblemDefinitionApiResponse =
  /** status 200 Success */ undefined;
export type UpdateProblemDefinitionApiArg = {
  id: string;
  updateProblemDefinitionRequest: UpdateProblemDefinitionRequest;
};
export type UpdateSustainingFactorDescriptionApiResponse =
  /** status 200 Success */ undefined;
export type UpdateSustainingFactorDescriptionApiArg = {
  analysisId: string;
  sustainingFactorId: string;
  updateDescriptionRequest: UpdateDescriptionRequest;
};
export type UpdateSustainingFactorPerceptiveTypeApiResponse =
  /** status 200 Success */ undefined;
export type UpdateSustainingFactorPerceptiveTypeApiArg = {
  analysisId: string;
  sustainingFactorId: string;
  updateSustainingFactorProducesRequest: UpdateSustainingFactorProducesRequest;
};
export type UpdateSustainingFactorSelectedForActionApiResponse =
  /** status 200 Success */ undefined;
export type UpdateSustainingFactorSelectedForActionApiArg = {
  analysisId: string;
  sustainingFactorId: string;
  updateSustainingFactorSelectedForActionRequest: UpdateSustainingFactorSelectedForActionRequest;
};
export type ErrorDetail = {
  code?: string;
  field?: string;
  attemptedValue?: any;
  message?: string;
};
export type ValidationError = {
  type?: string;
  title?: string;
  detail?: string;
  instance?: string;
  status?: number;
  traceId?: string;
  errors?: ErrorDetail[];
};
export type Error = {
  type?: string;
  title?: string;
  detail?: string;
  instance?: string;
  status?: number;
  traceId?: string;
};
export type AuthenticateRequest = {
  email: string;
  password: string;
};
export type CreateAnalysisStudyResponse = {
  id?: string;
};
export type CreateAnalysisStudyRequest = {
  title?: string;
};
export type AnalysisStudyItem = {
  id?: string;
  createdAt?: string;
  title?: string;
};
export type PerceptiveType =
  | "PerceptiveNotSelected"
  | "Individual"
  | "Context"
  | "Participant";
export type CreateSustainingFactorRequest = {
  description?: string;
  perceptiveType?: PerceptiveType;
  selectedForAction?: boolean;
};
export type CreateUserAccountRequest = {
  email?: string;
  password?: string;
};
export type ProblemDescription = {
  goal?: string;
  problemDefinition?: string;
  empiricalFoundation?: string;
  objective?: string;
};
export type AnalysisStudy = {
  id?: string;
  createdAt?: string;
  title?: string;
  problemDescription?: ProblemDescription;
};
export type RevokenTokenRequest = {
  refreshToken?: string;
};
export type UpdateEmpiricalFoundationRequest = {
  empiricalFoundation?: string;
};
export type UpdateGoalRequest = {
  goal?: string;
};
export type UpdateObjectiveRequest = {
  objective?: string;
};
export type UpdateProblemDefinitionRequest = {
  problemDefinition?: string;
};
export type UpdateDescriptionRequest = {
  description?: string;
};
export type UpdateSustainingFactorProducesRequest = {
  perceptiveType?: PerceptiveType;
};
export type UpdateSustainingFactorSelectedForActionRequest = {
  selectedForAction?: boolean;
};
export const {
  useAuthenticateMutation,
  useCreateAnalysisStudyMutation,
  useGetAnalysisStudiesQuery,
  useCreateSustainingFactorQuery,
  useCreateUserAccountMutation,
  useDeleteSustainingFactorMutation,
  useGetAnalysisStudyQuery,
  useRefreshTokenMutation,
  useRevokeTokenMutation,
  useUpdateEmpiricalFoundationMutation,
  useUpdateGoalMutation,
  useUpdateObjectiveMutation,
  useUpdateProblemDefinitionMutation,
  useUpdateSustainingFactorDescriptionMutation,
  useUpdateSustainingFactorPerceptiveTypeMutation,
  useUpdateSustainingFactorSelectedForActionMutation,
} = api;
`

**Comment by phryneas** [comment]
Ah, I see. These are missing `required`, so they are marked as "optional". The `?` allows for the property not being present, not for the value `null`. `nullable` would allow for `null`, which is something entirely different.

https://swagger.io/specification/#schema-object references the json-schema spec:
https://json-schema.org/understanding-json-schema/reference/object.html#required-properties

**Comment by JohnnyDP** [comment]
That seems to be it. Thank you very much for your help!
