### ISSUE TITLE
[Request] add support for generating enums

### ISSUE THREAD

**Issue by awdyson** [rtk-incubator/rtk-query-codegen#76]
Would love to see support for something like this:
https://github.com/ferdikoomen/openapi-typescript-codegen#enums-vs-union-types---useuniontypes

Also, is there a forum/discord/whatever for this sort of thing?
I know a flood of "great ideas" isn't always helpful, but it'd be nice to see what's being talked about and worked on.

**Comment by phryneas** [comment]
You can find one of us a lot of the time in #redux on Reactiflux.

As for Type-related features, we are just using the codegen from https://github.com/cellular/oazapfts, so probably asking there if it would be welcome as a feature and filing a PR over there is the best step.

**Comment by awdyson** [comment]
Thanks for the info.
