### ISSUE TITLE
Add Endpoint URLs to Generated API Field

### ISSUE THREAD

**Issue by grumpyTofu** [rtk-incubator/rtk-query-codegen#79]
I have been following the RTK docs to create a custom baseQuery with re-auth and ended up with something like:

```ts
export const apiBaseQueryReAuth: BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError> = async (args, api, extraOptions) => {
  let result = await apiBaseQuery(args, api, extraOptions);
  if (result.error && result.error.status === 401) {
    // try to get a new token
    const refreshResult = await apiBaseQuery("/api/auth/refresh", api, extraOptions);
    if (refreshResult.meta?.response?.status === 200 && refreshResult.data) {
      // store the new token
      api.dispatch(refreshAuth(refreshResult.data as AuthenticateApiResponse));
      // retry the initial query
      result = await apiBaseQuery(args, api, extraOptions);
    } else {
      // logout
      api.dispatch(deauth());
    }
  }
  return result;
};
```

However, I had to end up hard coding the authentication refresh endpoint instead of using a variable from the generated file. I am not sure if it is possible to use the auth refresh query created in the generated file, but if not, would there be a possibility of having the generated file output a list of all endpoints? This way, we could use the url values in different areas as well.

**Comment by phryneas** [comment]
With #81, the whole `baseQuery` handling (including urls) is now out of scope of the codegen, so I think this would not be an issue over there? But I might be misunderstanding the issue a bit.

Could you elaborate a bit further?

**Comment by grumpyTofu** [comment]
@phryneas yes, I can;

in this line:
```ts
const refreshResult = await apiBaseQuery("/api/auth/refresh", api, extraOptions);
```
notice the endpoint for auth refresh is hardcoded. 

Below is an example of my generated api endpoints:

```ts
export const api = createApi({
  baseQuery: apiBaseQueryReAuth,
  tagTypes: [],
  endpoints: (build) => ({
    // other endpoints
    refresh: build.query<RefreshApiResponse, RefreshApiArg>({
      query: () => ({ url: `/api/auth/refresh` }),
    }),
  }),
});
```

instead of hardcoding that URL, I am wondering if there would be a way to use the generated client to insert that value instead of hardcoding it. As far as I can see right now, we only get methods and types, which is all that is needed more most scenarios. However, I am also thinking that it won't be possible to just use that query inside of my custom base query. If I am wrong, maybe you could help me understand how to go about that, or I was wondering if the codegen could be updated to also output a list of endpoint urls in some type of object? This way, we could use it to reference the actual url of the endpoint when we need to do some custom stuff.

Essentially, I want to turn this:
```ts
const refreshResult = await apiBaseQuery("/api/auth/refresh", api, extraOptions);
```
into something like this:
```ts
const refreshResult = await apiBaseQuery(api.endpoints.refresh.url, api, extraOptions);
```

**Comment by grumpyTofu** [comment]
Closing this as this was no longer an issue with the customized baseQuery
